#
# Announcer configuration
# Author: AKANE AKAGI (akaregi)
# License: GPLv3
#
# Prefix and Messages support color code.
#

general:
  prefix: "Akikawa_: "
  # Unit: Second
  period: 600

messages:
  - "&aThis is first"
  - "&bThis is second"
  - "&cThis is third"