#
# Announcer configuration
# Author: AKANE AKAGI (akaregi)
# License: GPLv3
#
# Prefix and Messages support color code.
#

general:
  prefix: "Akikawa_: "
  # Unit: Second
  period: 1

messages:
  - "&aThis is first\n&aAnd then there's a secondary text. "
  - "&bThis is second"
  - "&cThis is third"